# Generated by Django 2.0.2 on 2018-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('desc', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=127)),
            ],
        ),
    ]
